version: '3.7'

services:
  backend:
    build: ./backend/
    ports:
      - "8000:8000"
    volumes:
      - ./backend/logs/:/app/logs/
    networks:
      - app-network
      
  frontend:
    build: ./frontend/
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge